spring:
  application:
    name: football-app
  config:
    import: "optional:file:.env[.properties]"

  datasource:
    url: jdbc:postgresql://localhost:5432/football_db
    username: ${PGUSER}
    password: ${PGPASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        default_schema: public

  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
    #use these temporarily after changes in sql scirpt
    #baseline-version: 0
    #validate-on-migrate: false

application:
  security:
    jwt:
      secret-key: ${JWT_SECRET}
      expiration: ${JWT_EXPIRATION:86400000}

springdoc:
  api-docs:
    version: OPENAPI_3_0
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: alpha
    tags-sorter: alpha
    disable-swagger-default-url: true
    persist-authorization: true
  writer-with-default-pretty-printer: true
  override-with-generic-response: true

---
spring:
  config:
    activate:
      on-profile: dev
